name: Deploy Web App to EC2
 
on:
  push:
    branches: [ "main" ]
 
jobs:
  deploy:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
 
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $EC2_PUBLIC_IP >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}
 
      - name: Deploy to EC2
        run: |
          scp -o StrictHostKeyChecking=no -r ./index.html $SSH_USERNAME@$EC2_PUBLIC_IP:/tmp/
          ssh $SSH_USERNAME@$EC2_PUBLIC_IP "sudo mv /tmp/index.html /var/www/html/index.html && sudo systemctl restart nginx || sudo systemctl restart httpd"
        env:
          EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}